---
version: '3'

vars:
  CLUSTER_NAME: gwkc-1
  GATEWAY_NS: gateway
  DEPENDENCIES:
    - docker
    - kind
    - cloud-provider-kind
    - kubectl

check-docker-running: &check-docker-running |
  docker info > /dev/null 2>&1

check-cluster-running: &check-cluster-running |
  kind get clusters | grep {{.CLUSTER_NAME}}

check-cloud-provider-kind-running: &check-cloud-provider-kind-running |
  pgrep sudo cloud-provider-kind

tasks:
  default:
    aliases: [all, make]
    deps:
      - check-dependencies
      - create-cluster
      - run-label-nodes
      - run-cloud-provider-kind
      - deploy-metrics-server
      - deploy-gateway
      - deploy-app
      #- update-etc-hosts
      - open-app

  check-dependencies:
    silent: true
    cmds:
      - |
        {{range .DEPENDENCIES}}
          if ! command -v {{.}} > /dev/null; then
            echo "{{.}} not found"
          fi
        {{end}}

  create-cluster:
    run: once
    preconditions:
      - *check-docker-running
    cmds:
      - kind create cluster --config=./1-install-kind/kind-config.yml
    status:
      - *check-cluster-running

  run-label-nodes:
    run: once
    deps:
      - create-cluster
    cmds:
      - |
        for node in $(kubectl get nodes -o name | grep "{{.CLUSTER_NAME}}-worker" | sed 's/.*\///'); do
          kubectl label nodes $node node-role.kubernetes.io/worker=""
        done

  run-cloud-provider-kind:
    run: once
    deps:
      - create-cluster
    interactive: true
    cmds:
      - sudo -v
      - zsh -c 'nohup sudo cloud-provider-kind --gateway-channel standard >/dev/null 2>&1 &'  # yamllint disable-line rule:line-length
    status:
      - *check-cloud-provider-kind-running

  deploy-gateway:
    run: once
    deps:
      - run-cloud-provider-kind
    cmds:
      - sleep 10  # wait for cloud-provider-kind to be ready
      - kubectl apply -f ./2-gateway-api/gateway.yml
      - kubectl wait gateway/gateway -n {{.GATEWAY_NS}} --for jsonpath='{.status.addresses[0].value}' 
    status:
      - kubectl diff -f ./2-gateway-api/gateway.yml

  clean-gateway:
    cmds:
      - kubectl delete -f ./2-gateway-api/app.yml

  deploy-metrics-server:
    run: once
    deps:
      - create-cluster
    cmds:
      - |
        kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml -n kube-system
        kubectl patch -n kube-system deployment metrics-server --type=json -p '[{"op":"add","path":"/spec/template/spec/containers/0/args/-","value":"--kubelet-insecure-tls"}]'
    status:
      - kubectl get deployment metrics-server -n kube-system

  clean-metrics-server:
    cmds:
      - kubectl delete -f https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml -n kube-system

  deploy-app:
    run: once
    deps:
      - deploy-gateway
    cmds:
      - kubectl apply -f ./2-gateway-api/app.yml
    status:
      - kubectl diff -f ./2-gateway-api/app.yml

  clean-app:
    cmds:
      - kubectl delete -f ./2-gateway-api/app.yml

  update-etc-hosts:
    run: once
    prompt: Do you want to update /etc/hosts ?
    deps:
      - deploy-app
    cmds:
      - kubectl wait gateway/gateway -n {{.GATEWAY_NS}} --for jsonpath='{.status.addresses[0].value}'
      - echo {{.LOAD_BALANCER_IP}}
      - sudo -v
      - echo "{{.LOAD_BALANCER_IP}}      kind.local" | sudo tee -a /etc/hosts
    status:
      - cat /etc/hosts | grep {{.LOAD_BALANCER_IP}}
    vars:
      LOAD_BALANCER_IP:
        sh: kubectl get gateway gateway -n {{.GATEWAY_NS}} | awk '{print $3}' | awk NR==2  # yamllint disable-line rule:line-length

  open-app:
    deps:
      - deploy-app
      - update-etc-hosts
    cmds:
      - open http://kind.local

  clean-cloud-provider-kind:
    interactive: true
    cmds:
      - *check-cloud-provider-kind-running
      - sudo -v
      - sudo pkill cloud-provider-kind

  clean-cluster:
    cmds:
      - kind delete cluster --name {{.CLUSTER_NAME}}

  clean-etc-hosts:
    cmds:
      - sudo -v
      - sudo sed -i '' '/kind\.local/d' /etc/hosts
      - echo "Removed all lines containing 'kind.local' from /etc/hosts"

  clean:
    aliases: [delete]
    ignore_error: true
    cmds:
      - task: clean-app
      - task: clean-gateway
      - task: clean-cluster
      - task: clean-cloud-provider-kind
     # - task: clean-etc-hosts