apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubevela
  namespace: argocd # Use the namespace where ArgoCD is installed
spec:
  project: default

  source:
    # Corresponds to 'helm repo add kubevela https://kubevela.github.io/charts'
    repoURL: https://kubevela.github.io/charts
    chart: vela-core
    targetRevision: "1.10.6" # Use a specific chart version for production
    helm:
      releaseName: kubevela
      values: |
        # Common defaults; adjust if needed.
        # If you want to pin images to a private registry, set image.registry / image.repository as supported by the chart.
        admissionWebhook:
          enabled: true

  destination:
    # Corresponds to '-n vela-system' (namespace must be pre-created)
    server: https://kubernetes.default.svc
    namespace: vela-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    
    # Corresponds to '--create-namespace' and part of '--wait' functionality
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
    # The 'helm install --wait' behavior is handled by ArgoCD's default health checks and sync status
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubevela-httproute
  namespace: argocd # Use the namespace where ArgoCD is installed
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default

  source:
    repoURL: https://github.com/adhatcher/kind-gateway-api.git
    targetRevision: main
    path: 8-kubevela
    directory:
      include: vela-httproute.yml

  destination:
    server: https://kubernetes.default.svc
    namespace: vela-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
