---
version: '3'

vars:
  CLUSTER_NAME: gwkc-1
  GATEWAY_NS: gateway
  DEPENDENCIES:
    - docker
    - kind
    - cloud-provider-kind
    - kubectl

check-docker-running: &check-docker-running |
  docker info > /dev/null 2>&1

check-cluster-running: &check-cluster-running |
  kind get clusters | grep {{.CLUSTER_NAME}}

check-cloud-provider-kind-running: &check-cloud-provider-kind-running |
  pgrep sudo cloud-provider-kind

tasks:
  default:
    aliases: [all, make]
    deps:
      - check-dependencies
      - run-cloud-provider-kind
      - deploy-gateway
      - deploy-app
      - update-etc-hosts
      - open-app

  check-dependencies:
    silent: true
    cmds:
      - |
        {{range .DEPENDENCIES}}
          if ! command -v {{.}} > /dev/null; then
            echo "{{.}} not found"
          fi
        {{end}}


  run-cloud-provider-kind:
    run: once
    deps:
      - create-cluster
    interactive: true
    cmds:
      - sudo -v
      - zsh -c 'nohup sudo cloud-provider-kind --gateway-channel standard >/dev/null 2>&1 &'  # yamllint disable-line rule:line-length
    status:
      - *check-cloud-provider-kind-running

  deploy-gateway:
    run: once
    deps:
      - run-cloud-provider-kind
    cmds:
      - sleep 5  # wait for cloud-provider-kind to be ready
      - kubectl apply -f gateway.yml
    status:
      - kubectl diff -f gateway.yml

  clean-gateway:
    cmds:
      - kubectl delete -f app.yml

  deploy-app:
    run: once
    deps:
      - deploy-gateway
    cmds:
      - kubectl apply -f app.yml
    status:
      - kubectl diff -f app.yml

  clean-app:
    cmds:
      - kubectl delete -f app.yml

  update-etc-hosts:
    run: once
    prompt: Do you want to update /etc/hosts ?
    deps:
      - deploy-app
    cmds:
      - echo {{.LOAD_BALANCER_IP}}
      - sudo -v
      - echo "{{.LOAD_BALANCER_IP}}      kind.local" | sudo tee -a /etc/hosts
    status:
      - cat /etc/hosts | grep {{.LOAD_BALANCER_IP}}
    vars:
      LOAD_BALANCER_IP:
        sh: kubectl get gateway/gateway -n {{.GATEWAY_NS}} | awk '{print $3}' | awk NR==2  # yamllint disable-line rule:line-length

  open-app:
    deps:
      - deploy-app
      - update-etc-hosts
    cmds:
      - open http://kind.local

  clean-cloud-provider-kind:
    interactive: true
    cmds:
      - *check-cloud-provider-kind-running
      - sudo -v
      - sudo pkill cloud-provider-kind

  clean-etc-hosts:
    cmds:
      - sudo -v
      - sudo sed -i '' '/kind\.local/d' /etc/hosts
      - echo "Removed all lines containing 'kind.local' from /etc/hosts"

  clean:
    aliases: [delete]
    ignore_error: true
    cmds:
      - task: clean-app
      - task: clean-gateway
      - task: clean-cloud-provider-kind
      - task: clean-etc-hosts