apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argocd-httproute
  namespace: argocd
spec:
  parentRefs:
    - name: gateway
      namespace: gateway
      sectionName: http
  hostnames:
    - "argocd.local"
  rules:
    - backendRefs:
        - name: argocd-server
          port: 80
