apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server-helm
  namespace: argocd
spec:
  project: default
  source:
    # Use the official source repository for metrics-server manifest definitions
    repoURL: https://github.com/kubernetes-sigs/metrics-server
    targetRevision: HEAD # Or a specific commit/tag if preferred
    path: charts/metrics-server # Points to the root of the Helm chart definition

    # --- Helm Specific Configuration ---
    helm:
      # Override values directly to add the insecure-tls flag
      values: |
        args:
          - --kubelet-insecure-tls=true
          # You might need other default args to be present, depending on the chart version
          # The official chart handles defaults, so we just add our required one.

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system # metrics-server usually runs here

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
