apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel
  namespace: argocd
spec:
  project: otel-project
  source:
    repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    targetRevision: '*'
    chart: opentelemetry-operator
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true