apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: cert-manager-project
  source:
    repoURL: https://charts.jetstack.io
    targetRevision: v1.14.0
    helm:
      parameters:
        - name: installCRDs
          value: 'true'
        - name: global.leaderElection.namespace
          value: cert-manager
    chart: cert-manager
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true