apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cluster-cert
  namespace: gateway
spec:
  dnsNames:
    - "mustang.k8s-dev"
    - "grafana.mustang.k8s-dev"
    - "argocd.mustang.k8s-dev"
    - "grafana.mustang.k8s-dev"
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
  secretName: cluster-tls-secret